version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    image: 'postgres:12.2'
    volumes:
      - 'local_postgres_data:/var/lib/postgresql/data'
      - 'local_postgres_data_backups:/backups'
    env_file:
      - local/environment
    ports:
      - '5433:5432'

  django:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: sixienote_local_django:dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - '.:/opt/project:z'
    env_file:
      - local/environment
    depends_on:
      - migrate
      - mailhog
      - redis
    links:
      - db
      - mailhog
      - redis
    ports:
      - '8000:8000'

  migrate:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: sixienote_local_django:dev
    command: python manage.py migrate
    volumes:
      - '.:/opt/project:z'
    env_file:
      - local/environment
    depends_on:
      - db
    links:
      - db

  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
    ports:
      - '8025:8025'

  redis:
    image: redis:latest
